### ISSUE TITLE
Data Visualization Exercise

### ISSUE THREAD

**Issue by Annabella-Hines** [kellyhatfield/kellyhatfield-MADA-portfolio#3]
Hi Kelly! I think you did a really great job tackling this graph; it wasn't the most familiar format but your version was pretty similar. I think you could maybe get the percentages on the bar using a geom_text layer with a y= in the aesthetics section to get it in the right spot on the bar. Here's an example of what might work 
geom_text(aes(label=, y=)
I am not exactly sure but that was my best guess. I'm impressed your colors are so similar and you were able to get all the pieces onto the graph. Also maybe to get the titles for each set of bars you could make each its own plot and then use ggarrange to put them together. Great job!

**Comment by kellyhatfield** [comment]
Thanks I added those suggestions.
