### ISSUE TITLE
whole site needs rebuilding

### ISSUE THREAD

**Issue by andreashandel** [kellyhatfield/kellyhatfield-MADA-portfolio#5]
I noticed that depending on if one clicks on prior sub-sections for the flu analysis, not all entries show up in the menu bar. This is likely because you rendered individual pages, but forgot to rebuild the full website at the end.
At some point, do build the whole website so one can get to every section no matter where on went previously.

**Comment by kellyhatfield** [comment]
Thanks Dr. Handel. I noticed that but wasn't sure how to fix it. I rebuilt the website and it seems to be fixed at this point.
